### PR TITLE
Two quick fixes for your executable

### PR DESCRIPTION
**Pull request by cldwalker**
Looking forward to this service!

### CODE REVIEW

**Comment by cldwalker** [comment]
would add some tests for all this but would need to move Dydra::CLI within lib

**Comment by bhuga** [comment]
Merged, thanks. You just jumped the line if you want to, email me at ben@dydra.com with the email address you signed up with.

**Comment by cldwalker** [comment]
Thanks as well :)

**Comment by artob** [comment]
Thanks, Gabriel. I've added you to the gem's contributors list as well.

**Pull request merged**
